# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
sudo: required

services:
   - docker

env:
  - PLATFORM_LANGUAGE=cpp
  - PLATFORM_LANGUAGE=java

cache:
  timeout: 900
  directories:
  - $HOME/.m2
  - $HOME/.ccache

branches:
  only:
  - master

before_cache:
  - sudo rm -rf $HOME/.m2/repository/com/yahoo
  - du --summarize --human-readable $HOME/.m2/repository
  - ccache --show-stats

install: true

language: minimal

script: travis_wait 120 ./travis/travis.sh $PLATFORM_LANGUAGE

